### ISSUE TITLE
bot works but issues with commands working

### ISSUE THREAD

**Issue by MoosesScripts** [i6h/priority-bot#1]
No handler available for this interaction (ApplicationCommand > removepriority)
![Screenshot 2024-08-13 173039](https://github.com/user-attachments/assets/92db070a-dd3a-4f48-ac84-26f96362b64d)

**Comment by its4lion** [comment]
is there anything on console and try last update

make sure these options on
![image](https://github.com/user-attachments/assets/10f289b9-f2ad-496c-b0a5-f510fb02ada4)

**Comment by MoosesScripts** [comment]
![Screenshot 2024-08-14 114830](https://github.com/user-attachments/assets/0f4f2ae4-8f0b-4d77-b211-21b1af26459c)

**Comment by its4lion** [comment]
check if the bot have permissions

**Comment by its4lion** [comment]
try download last bot update @LYCoreFramework  😊

**Comment by MoosesScripts** [comment]
do i give my bot all permissions i also downloaded update [v1.0.4](https://github.com/i6h/priority-bot/releases/tag/v1.0.4)

**Comment by MoosesScripts** [comment]
that older update still dont work i have lateset this is what i get in the console
![Screenshot 2024-08-14 213601](https://github.com/user-attachments/assets/2921d24d-dd41-4986-b17f-fb6310e620d1)

but i still get No handler available for this interaction (ApplicationCommand > givepriority)

**Comment by its4lion** [comment]
@LYCoreFramework , Please check if it's working now. If you encounter any issues or see the "No handler available" error, message me on Discord `@its4lion`.

Thanks!
